# Generated by Django 4.2.20 on 2025-04-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_symbol', models.CharField(default='BTC_USDT', help_text='Trading pair symbol (e.g., BTC_USDT)', max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('decimal_precision', models.IntegerField(default=4)),
                ('risk_tolerance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trade_volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('time_interval', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pair_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('exchange_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('bot_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.botconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bot.botconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.exchange'),
        ),
    ]
