# Generated by Django 4.2.20 on 2025-04-28 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='status',
            field=models.CharField(default='idle', max_length=255),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bot_configurations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
