# Generated by Django 4.2.20 on 2025-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botconfiguration_status_botconfiguration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='api_endpoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
