# Generated by Django 4.2.20 on 2025-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_exchange_api_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='passphrase',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
