# Generated by Django 4.2.20 on 2025-05-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botconfiguration_passphrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfiguration',
            old_name='passphrase',
            new_name='memo',
        ),
    ]
